### ISSUE TITLE
Updating the domain lists

### ISSUE THREAD

**Issue by stac47** [smudge/freemail#20]
Hello dear maintainers,

First of all thanks for your work on this gem. Kudo!

I was looking at the domains list and probably the lists have been growing for the last 3 years.
I was wondering whether we could update it from time to time. For this I was thinking to [this](https://github.com/7c/fakefilter) which provides frequently updated a list in different formats.

I would be glad to hear your opinion and, if needed, would be happy to contribute.

**Comment by smudge** [comment]
Hi @stac47! I'm always happy to accept PRs for updates to `free.txt` and `disposable.txt`, but since it has been a while, I also went ahead and released a new version. (The lists get synced from the npm `freemail` package.)

**Comment by stac47** [comment]
Big thank you!
