### ISSUE TITLE
Check permissions on data files of the released gem

### ISSUE THREAD

**Issue by meineerde** [smudge/freemail#7]
The currently released gem version 0.2.0 has different file permissions on the data file. Specifically, the `disposable.txt` is not world-readable:

```
-rw-r----- 1 user group  4695 Oct  4 17:04 disposable.txt
-rw-r--r-- 1 user group 50937 Oct  4 17:04 free.txt
```

This results in file access errors in our deployment environment since the actual application user is not allowed to read the file anymore after the gem was installed by a different user.

It would be great if you could release a new version (maybe even with the current state of the data :) ) which ensures that all the files are world-readable. For this, you probably need to change the file permission in your local checkout where build and push the gem.

**Comment by smudge** [comment]
Interesting! Will have to wait until tonight to take a look at this. I'll try to get this included when I cut a new version with the changes from today.

**Comment by smudge** [comment]
New version is out - `0.2.1`

File permissions should be fixed. Let me know if you're not seeing it.

**Comment by meineerde** [comment]
The gem looks fine now.

Thank you for your quick help! Would buy again :) 🎉👍

**Comment by ehsanidme** [comment]
@smudge I think the same issue is happening for version `0.6.0`. Could you publish a new version with the fixed permissions?

**Comment by smudge** [comment]
@ehsanidme 🤦 `0.6.1` is out and should fix file permissions. LMK if you're still seeing any issues.

**Comment by ehsanidme** [comment]
@smudge Thank you!
